### ISSUE TITLE
All the 4 game samples are bugged

### ISSUE THREAD

**Issue by KenshirouLuke** [craftworkgames/MonoGame.Extended-samples#16] opened 2024-09-13 13:08 UTC
Hi, launching the 4 games results in clear bug at a drawing level:

- Platformer: the entitites are shifted down respect to the terrain;
- Pong: the enemy paddle get stucked with its center across the bottomline, and ball reflection is weird on player's paddle corner;
- SpaceGame: the shoots are fired shifted to one side respect to the position of the ship;
- StarWarrior: the fire function seems to not have effect, there is only a growing mess of sprites and texts across the screen.

So I thought that something changed in the library across the time, and I updated all the the 5 Nuget references in each project, since were old, updating also the .NET projects' version to 8.0 to be compliant with the new Nuget versions... but now none of the projects compile, all giving the same error related to the MGCB:

**The command "dotnet mgcb /quiet** /@:"C:\Users\lucia\Downloads\MonoGame.Extended-samples-main\src\Games\[PROJECT-NAME]\Content\Content.mgcb" /platform:DesktopGL /outputDir:"C:/[MY-PATH]/MonoGame.Extended-samples-main/src/Games/StarWarrior/Content/bin/DesktopGL/Content" /intermediateDir:"C:/[MY-PATH]/MonoGame.Extended-samples-main/src/Games/StarWarrior/Content/obj/DesktopGL/net8.0/Content" /workingDir:"C:/[MY-PATH]/MonoGame.Extended-samples-main/src/Games/StarWarrior/Content/"" **exited with code 1.**[PROJECT-NAME] C:\[MY-PATH]\.nuget\packages\monogame.content.builder.task\3.8.2.1105\build\MonoGame.Content.Builder.Task.targets	143

Where I replaced my local paths with values in square brackets.

Monogame.Extended seems interesting, but if even the demo projects are bugged or not starting, it's hard to trust using it...

Can someone fix those projects, in order to provide a starting point for who need to see how to use this library?
Thanks.

**Comment by kaltinril** [comment] 2024-09-22 22:25
I'll see if I can take a look at some of these.

I've submitted PR's for the other demos and samples items
PR #17
PR #18

**Comment by kaltinril** [comment] 2024-09-23 02:47
The cause of the Pong Paddle getting stuck, and "teleporting" when going to the top/bottom are related to an issue that was introduced in Monogame.Extended.  I've opened an Issue here

https://github.com/craftworkgames/MonoGame.Extended/issues/950

**Comment by kaltinril** [comment] 2024-09-23 03:02
I wonder if the causes of your other first 2 items are also the MonoGame.Extended.Graphics.Sprite.OriginNormalized code.

**Comment by kaltinril** [comment] 2024-09-23 03:44
Yeah, the spacegame ship is also not centered.

![image](https://github.com/user-attachments/assets/e504a3ef-8192-4d49-9404-9fc74b0bc973)

**Comment by kaltinril** [comment] 2024-10-11 06:44
I forgot to comment here, the 4.0.3 revert fixes MOST of these items.  I first updated all them to 4.0.2 hoping that would fix it but it didn't after the revert that happened in 4.0.3 I tested and they are working now.

I'm working on getting the projects updated to be using the 4.0.3.

The StarWarrior still has issues though in 4.0.3, this isn't related to Extended, its just coding that needs to be updated.

(I swear I added a comment somewhere but maybe I forgot to click save)

**Comment by kaltinril** [comment] 2024-11-05 23:11
Adding images showing the image issues are fixed with the revert from last month:
![image](https://github.com/user-attachments/assets/9059c950-d8eb-4afa-8fad-6606e2276447)
![image](https://github.com/user-attachments/assets/810c0d8c-26ff-46ff-b9d6-1dc84c78b201)
![image](https://github.com/user-attachments/assets/36cae916-22ba-45f9-a5bd-3f2d9159da96)

StarWarrior doesn't appear to be a complete game  @AristurtleDev @KenshirouLuke the main issues that related to the offset of the images were resolved.  I think this issue should be closed, and a new one opened specifically for someone to finish the StarWarrior "Game".  I started to work on limiting the number of EnemyShips but noticed many other issues with StarWarrior.
1. Bullets can only be fired every 2 seconds, if you fire when you're not supposed to, your bullets disappear.
2. Bullets disappear when you can't fire them
3. Enemies spawn every update frame, without bounds or restrictions on the number of enemies
4. Enemies are not drawn if he player is off the screen
5. Collision detection with enemies and bullets, and player and bullets do not happen.
6. Enemies bounce off the walls from the CENTER, so half of their ship goes off each side.

I have no experience with ECS, and I'd hate to mix different coding paradigms by my lack of knowledge on Entity Component Systems.

**Comment by kaltinril** [comment] 2024-11-05 23:12
StarWarrior doesn't appear to be a complete game  @AristurtleDev @KenshirouLuke the main issues that related to the offset of the images were resolved.  I think this issue should be closed, and a new one opened specifically for someone to finish the StarWarrior "Game".  I started to work on limiting the number of EnemyShips but noticed many other issues with StarWarrior.
1. Bullets can only be fired every 2 seconds, if you fire when you're not supposed to, your bullets disappear.
2. Bullets disappear when you can't fire them
3. Enemies spawn every update frame, without bounds or restrictions on the number of enemies
4. Enemies are not drawn if he player is off the screen
5. Collision detection with enemies and bullets, and player and bullets do not happen.
6. Enemies bounce off the walls from the CENTER, so half of their ship goes off each side.

I have no experience with ECS, and I'd hate to mix different coding paradigms by my lack of knowledge on Entity Component Systems.

![image](https://github.com/user-attachments/assets/67cdcd6e-6eb9-4669-aa1a-b2f60f98ed52)

**Comment by kaltinril** [comment] 2024-11-20 09:50
I've submitted a PR to fix the game now

**Comment by johannes-el** [comment] 2024-12-01 10:08
In the platformer there are still more bugs, namely:
* The player can get stuck between the two enemies.
* The player can get pushed out of the world from the right enemy.

**Comment by kaltinril** [comment] 2024-12-01 19:41
> In the platformer there are still more bugs, namely:
> 
> * The player can get stuck between the two enemies.
> * The player can get pushed out of the world from the right enemy.

Two thoughts from a random contributer.
1. Any new observations please open a new issue.
2. I don't know if these samples are supposed to be anything other than examples to get someone started. I don't think they claim to be complete games.


I'll let @AristurtleDev respond officially.

**Closed** 2024-12-02 00:59 UTC

**Comment by AristurtleDev** [comment] 2024-12-02 01:04
> 2\. I don't know if these samples are supposed to be anything other than examples to get someone started. I don't think they claim to be complete games.

They aren't going to be "complete" games, but we should strive to have them as bug free samples.  

@johannes-el could you open a separate issue for the Platformer sample
